In [1]:
import numpy as np

In [2]:
x = np.linspace(-1, 1, 5)
y = np.linspace(-1, 1, 5)
x, y, x.shape, y.shape

(array([-1. , -0.5,  0. ,  0.5,  1. ]),
 array([-1. , -0.5,  0. ,  0.5,  1. ]),
 (5,),
 (5,))

In [3]:
xx, yy = np.meshgrid(x, y)
xx, yy, xx.shape, yy.shape

(array([[-1. , -0.5,  0. ,  0.5,  1. ],
        [-1. , -0.5,  0. ,  0.5,  1. ],
        [-1. , -0.5,  0. ,  0.5,  1. ],
        [-1. , -0.5,  0. ,  0.5,  1. ],
        [-1. , -0.5,  0. ,  0.5,  1. ]]),
 array([[-1. , -1. , -1. , -1. , -1. ],
        [-0.5, -0.5, -0.5, -0.5, -0.5],
        [ 0. ,  0. ,  0. ,  0. ,  0. ],
        [ 0.5,  0.5,  0.5,  0.5,  0.5],
        [ 1. ,  1. ,  1. ,  1. ,  1. ]]),
 (5, 5),
 (5, 5))

In [4]:
xx1 = xx.flatten()
yy1 = yy.flatten()
xx1, yy1, xx1.shape, yy1.shape

(array([-1. , -0.5,  0. ,  0.5,  1. , -1. , -0.5,  0. ,  0.5,  1. , -1. ,
        -0.5,  0. ,  0.5,  1. , -1. , -0.5,  0. ,  0.5,  1. , -1. , -0.5,
         0. ,  0.5,  1. ]),
 array([-1. , -1. , -1. , -1. , -1. , -0.5, -0.5, -0.5, -0.5, -0.5,  0. ,
         0. ,  0. ,  0. ,  0. ,  0.5,  0.5,  0.5,  0.5,  0.5,  1. ,  1. ,
         1. ,  1. ,  1. ]),
 (25,),
 (25,))

In [5]:
coordinate = np.concatenate((xx1[:, None], yy1[:, None]), axis=-1)
coordinate, coordinate.shape

(array([[-1. , -1. ],
        [-0.5, -1. ],
        [ 0. , -1. ],
        [ 0.5, -1. ],
        [ 1. , -1. ],
        [-1. , -0.5],
        [-0.5, -0.5],
        [ 0. , -0.5],
        [ 0.5, -0.5],
        [ 1. , -0.5],
        [-1. ,  0. ],
        [-0.5,  0. ],
        [ 0. ,  0. ],
        [ 0.5,  0. ],
        [ 1. ,  0. ],
        [-1. ,  0.5],
        [-0.5,  0.5],
        [ 0. ,  0.5],
        [ 0.5,  0.5],
        [ 1. ,  0.5],
        [-1. ,  1. ],
        [-0.5,  1. ],
        [ 0. ,  1. ],
        [ 0.5,  1. ],
        [ 1. ,  1. ]]),
 (25, 2))

In [7]:
# 不对，不应该这样做
coordinate = coordinate.reshape(5, 5, -1)
coordinate, coordinate.shape

(array([[[-1. , -1. ],
         [-0.5, -1. ],
         [ 0. , -1. ],
         [ 0.5, -1. ],
         [ 1. , -1. ]],
 
        [[-1. , -0.5],
         [-0.5, -0.5],
         [ 0. , -0.5],
         [ 0.5, -0.5],
         [ 1. , -0.5]],
 
        [[-1. ,  0. ],
         [-0.5,  0. ],
         [ 0. ,  0. ],
         [ 0.5,  0. ],
         [ 1. ,  0. ]],
 
        [[-1. ,  0.5],
         [-0.5,  0.5],
         [ 0. ,  0.5],
         [ 0.5,  0.5],
         [ 1. ,  0.5]],
 
        [[-1. ,  1. ],
         [-0.5,  1. ],
         [ 0. ,  1. ],
         [ 0.5,  1. ],
         [ 1. ,  1. ]]]),
 (5, 5, 2))